CREATE TABLE bid (
                     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                     sum NUMERIC(10,2),
                     lot_id BIGINT,
                     created_at TIMESTAMP DEFAULT NOW(),
                     updated_at TIMESTAMP DEFAULT NOW(),
                     deleted_at TIMESTAMP,
                     version BIGINT DEFAULT 0,
                     CONSTRAINT fk_bid_lot FOREIGN KEY (lot_id) REFERENCES lot (id) ON DELETE CASCADE ON UPDATE CASCADE
);